version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      # Lee la URL de la base de datos externa desde tu .env
      - DATABASE_URL=${DATABASE_URL}
    # Comando de producción real, sin el --reload
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000