version: '3.8'

services:
  app:
    image: proyecto-de-desarrollo-app:latest
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME} 