services:
  app:
    image: proyecto_pdf:v1.0.0  
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Lee el .env que está en esta misma carpeta docker
    networks:
      - redutn
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

networks:
  redutn:
    external: true